package com.jvmobservability.demo.controller;

import io.micrometer.core.instrument.Counter;
import io.micrometer.core.instrument.MeterRegistry;
import io.micrometer.core.instrument.Timer;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;
import java.time.Instant;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.concurrent.ThreadLocalRandom;
import java.util.concurrent.TimeUnit;

/**
 * ObservabilityController — pipeline inspection and traffic simulation.
 *
 * ┌──────────────────────────────────────────────────────────────────────────┐
 * │  Endpoints                                                                │
 * │                                                                           │
 * │  GET  /api/observability/pipeline                                         │
 * │       → Shows live health of every layer in the OTel pipeline            │
 * │       → Use this to verify data is flowing end-to-end                    │
 * │                                                                           │
 * │  POST /api/observability/simulate?type=latency|errors|traffic&count=N    │
 * │       → Generates artificial metric events for Kibana testing             │
 * │       → Creates real ES documents you can immediately query              │
 * │                                                                           │
 * │  GET  /api/observability/es-snapshot                                      │
 * │       → Queries Elasticsearch directly and returns the last 5            │
 * │          metric documents — proves end-to-end data flow                  │
 * └──────────────────────────────────────────────────────────────────────────┘
 */
@RestController
@RequestMapping("/api/observability")
public class ObservabilityController {

    private static final Logger log = LoggerFactory.getLogger(ObservabilityController.class);

    @Value("${management.otlp.metrics.export.url:http://localhost:4318/v1/metrics}")
    private String otlpUrl;

    @Value("${elasticsearch.url:http://localhost:9200}")
    private String elasticsearchUrl;

    private final MeterRegistry meterRegistry;

    // Simulation counters — created fresh per JVM session
    private final Counter simulatedTraffic;
    private final Counter simulatedErrors;
    private final Timer   simulatedLatency;

    public ObservabilityController(MeterRegistry meterRegistry) {
        this.meterRegistry = meterRegistry;

        this.simulatedTraffic = Counter.builder("sim.requests.total")
                .description("Simulated traffic generated by /api/observability/simulate")
                .tag("source", "simulation")
                .register(meterRegistry);

        this.simulatedErrors = Counter.builder("sim.errors.total")
                .description("Simulated errors generated by /api/observability/simulate")
                .tag("source", "simulation")
                .register(meterRegistry);

        this.simulatedLatency = Timer.builder("sim.request.duration")
                .description("Simulated request latency generated by /api/observability/simulate")
                .tag("source", "simulation")
                .publishPercentileHistogram()
                .publishPercentiles(0.5, 0.95, 0.99)
                .register(meterRegistry);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // GET /api/observability/pipeline
    //
    // Probes every layer of the OTel pipeline and returns a health map.
    // Call this after starting the stack to confirm end-to-end connectivity.
    //
    // Example response:
    // {
    //   "layers": {
    //     "spring_actuator":       { "status": "UP", "url": "http://localhost:8080/actuator/metrics" },
    //     "otlp_endpoint":         { "status": "UP", "url": "http://localhost:4318" },
    //     "otel_collector_health": { "status": "UP", "url": "http://localhost:13133" },
    //     "prometheus_scrape":     { "status": "UP", "url": "http://localhost:8889/metrics" },
    //     "elasticsearch":         { "status": "UP", "docs_in_otel_metrics": 1240 },
    //     "kibana":                { "status": "UP", "url": "http://localhost:5601" }
    //   },
    //   "otlp_push_interval": "10s",
    //   "metric_count_in_registry": 84
    // }
    // ─────────────────────────────────────────────────────────────────────────
    @GetMapping("/pipeline")
    public ResponseEntity<Map<String, Object>> pipelineStatus() {
        HttpClient client = HttpClient.newBuilder()
                .connectTimeout(Duration.ofSeconds(3))
                .build();

        Map<String, Object> layers = new LinkedHashMap<>();

        // Layer 1: Spring Actuator
        layers.put("1_spring_actuator", probe(client,
                "http://localhost:8080/actuator/health",
                "http://localhost:8080/actuator/metrics"));

        // Layer 2: OTel Collector OTLP receiver (push target)
        // We can't GET the OTLP gRPC/HTTP receiver — check health endpoint instead
        layers.put("2_otel_collector_health", probe(client,
                "http://localhost:13133",
                "http://localhost:13133"));

        // Layer 2b: Prometheus scrape endpoint (OTel Collector exposes this)
        layers.put("2b_prometheus_scrape_endpoint", probe(client,
                "http://localhost:8889/metrics",
                "http://localhost:8889/metrics"));

        // Layer 3: Elasticsearch
        Map<String, Object> esStatus = probeElasticsearch(client);
        layers.put("3_elasticsearch", esStatus);

        // Layer 4: Kibana
        layers.put("4_kibana", probe(client,
                "http://localhost:5601/api/status",
                "http://localhost:5601"));

        Map<String, Object> result = new LinkedHashMap<>();
        result.put("timestamp",              Instant.now().toString());
        result.put("layers",                 layers);
        result.put("otlp_push_interval",     "10s");
        result.put("otlp_target",            otlpUrl);
        result.put("metric_count_in_registry", meterRegistry.getMeters().size());
        result.put("next_push_in",           "up to 10s (micrometer-registry-otlp step)");

        return ResponseEntity.ok(result);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // POST /api/observability/simulate?type=traffic|errors|latency&count=50
    //
    // Generates metric events and pushes them into the OTel pipeline.
    // Wait 10s then check Kibana — you should see the values change.
    //
    // type=traffic  → sim.requests.total counter increments by count
    // type=errors   → sim.errors.total   counter increments by count
    // type=latency  → sim.request.duration histogram records count samples
    //                  (random 5ms - 2000ms to create a realistic distribution)
    // ─────────────────────────────────────────────────────────────────────────
    @PostMapping("/simulate")
    public ResponseEntity<Map<String, Object>> simulate(
            @RequestParam(defaultValue = "traffic") String type,
            @RequestParam(defaultValue = "10")      int count) {

        count = Math.min(count, 1000); // cap at 1000 to avoid overload

        long emitted = 0;

        switch (type.toLowerCase()) {
            case "traffic" -> {
                for (int i = 0; i < count; i++) simulatedTraffic.increment();
                emitted = count;
            }
            case "errors" -> {
                for (int i = 0; i < count; i++) simulatedErrors.increment();
                emitted = count;
            }
            case "latency" -> {
                // Simulate bimodal distribution: fast (5-50ms) + occasional slow (500-2000ms)
                for (int i = 0; i < count; i++) {
                    long ms = ThreadLocalRandom.current().nextInt(100) < 90
                            ? ThreadLocalRandom.current().nextLong(5, 50)      // 90% fast
                            : ThreadLocalRandom.current().nextLong(500, 2000); // 10% slow
                    simulatedLatency.record(ms, TimeUnit.MILLISECONDS);
                }
                emitted = count;
            }
            default -> {
                return ResponseEntity.badRequest().body(Map.of(
                        "error", "unknown type '" + type + "', use: traffic | errors | latency"));
            }
        }

        log.info("[OTel Simulation] Emitted {} '{}' events. Will appear in Elasticsearch in ~10s.", emitted, type);

        Map<String, Object> resp = new LinkedHashMap<>();
        resp.put("type",            type);
        resp.put("events_emitted",  emitted);
        resp.put("metric_name",     switch (type) {
            case "traffic" -> "sim.requests.total";
            case "errors"  -> "sim.errors.total";
            default        -> "sim.request.duration";
        });
        resp.put("appears_in_es_in", "~10 seconds (OTLP push interval)");
        resp.put("kibana_query",     "name: \"" + resp.get("metric_name") + "\"");
        resp.put("es_query",
                "curl -s \"" + elasticsearchUrl + "/otel-metrics/_search?pretty\" " +
                "-H 'Content-Type: application/json' " +
                "-d '{\"query\":{\"term\":{\"name\":\"" + resp.get("metric_name") + "\"}},\"size\":3,\"sort\":[{\"@timestamp\":\"desc\"}]}'");

        return ResponseEntity.ok(resp);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // GET /api/observability/es-snapshot
    //
    // Queries Elasticsearch directly from the app and returns the last 5
    // metric documents from otel-metrics.
    // Proves that data is flowing all the way from Spring Boot → ES.
    //
    // If this returns empty: wait 10s for the next OTLP push, then retry.
    // ─────────────────────────────────────────────────────────────────────────
    @GetMapping("/es-snapshot")
    public ResponseEntity<Map<String, Object>> esSnapshot(
            @RequestParam(defaultValue = "music.song.upload.total") String metricName) {

        HttpClient client = HttpClient.newBuilder()
                .connectTimeout(Duration.ofSeconds(5))
                .build();

        String query = """
                {
                  "query": { "term": { "name": "%s" } },
                  "size": 5,
                  "sort": [{ "@timestamp": { "order": "desc" } }],
                  "_source": ["@timestamp", "name", "description", "unit",
                              "sum", "gauge", "histogram",
                              "resource.attributes.service.name",
                              "attributes.service",
                              "attributes.environment"]
                }
                """.formatted(metricName);

        try {
            HttpRequest req = HttpRequest.newBuilder()
                    .uri(URI.create(elasticsearchUrl + "/otel-metrics/_search"))
                    .timeout(Duration.ofSeconds(8))
                    .header("Content-Type", "application/json")
                    .POST(HttpRequest.BodyPublishers.ofString(query))
                    .build();

            HttpResponse<String> resp = client.send(req, HttpResponse.BodyHandlers.ofString());

            Map<String, Object> result = new LinkedHashMap<>();
            result.put("queried_metric",   metricName);
            result.put("elasticsearch_url", elasticsearchUrl + "/otel-metrics/_search");
            result.put("http_status",      resp.statusCode());
            result.put("tip",
                    "If hits.total.value=0: wait 10s for OTLP push, " +
                    "call POST /api/songs/bulk first to generate traffic, then retry.");
            result.put("raw_response",     resp.body());

            return ResponseEntity.ok(result);

        } catch (Exception e) {
            return ResponseEntity.ok(Map.of(
                    "error",           "Could not reach Elasticsearch at " + elasticsearchUrl,
                    "message",         e.getMessage(),
                    "fix",             "Ensure docker compose is running: docker compose ps"
            ));
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Helpers
    // ─────────────────────────────────────────────────────────────────────────

    private Map<String, Object> probe(HttpClient client, String checkUrl, String displayUrl) {
        Map<String, Object> result = new LinkedHashMap<>();
        result.put("url", displayUrl);
        try {
            HttpRequest req = HttpRequest.newBuilder()
                    .uri(URI.create(checkUrl))
                    .timeout(Duration.ofSeconds(3))
                    .GET()
                    .build();
            HttpResponse<Void> resp = client.send(req, HttpResponse.BodyHandlers.discarding());
            result.put("status",      resp.statusCode() < 400 ? "UP" : "DOWN");
            result.put("http_status", resp.statusCode());
        } catch (Exception e) {
            result.put("status",  "DOWN");
            result.put("reason",  e.getMessage());
        }
        return result;
    }

    private Map<String, Object> probeElasticsearch(HttpClient client) {
        Map<String, Object> result = new LinkedHashMap<>();
        result.put("url", elasticsearchUrl);
        try {
            // Cluster health
            HttpRequest healthReq = HttpRequest.newBuilder()
                    .uri(URI.create(elasticsearchUrl + "/_cluster/health"))
                    .timeout(Duration.ofSeconds(3))
                    .GET()
                    .build();
            HttpResponse<String> healthResp = client.send(healthReq, HttpResponse.BodyHandlers.ofString());
            result.put("status",         healthResp.statusCode() == 200 ? "UP" : "DOWN");
            result.put("cluster_health", healthResp.body());

            // otel-metrics doc count
            HttpRequest countReq = HttpRequest.newBuilder()
                    .uri(URI.create(elasticsearchUrl + "/otel-metrics/_count"))
                    .timeout(Duration.ofSeconds(3))
                    .GET()
                    .build();
            HttpResponse<String> countResp = client.send(countReq, HttpResponse.BodyHandlers.ofString());
            result.put("otel_metrics_docs", countResp.body());

        } catch (Exception e) {
            result.put("status", "DOWN");
            result.put("reason", e.getMessage());
        }
        return result;
    }
}
